Pull request for TSE Review
fdfragoso/responsive-design-tnw pull request #2
Opened 2020-04-01 10:19 UTC by fdfragoso

- All the features added as aked on pathwright and Odin project;
- Linters and HTML validator checked;
- Responsive added and tested with Chrome and Firefox;
- Waiting for feedback.

2020-04-01 13:19 UTC, christianotieno requested changes
# **CHANGES REQUIRED** :warning:
Hey @fdfragoso   & @JelilFaisalAbudu   :wave:
-
Good job so far! :tada: We have some few changes to do before we proceed (see review comment).

## [REQUIRED] - ADD - Missing list items.
In the nav-centre section, the growth quarters and neural list items are missing:
Heres yours: 👇 
![nav_centre_clone](https://user-images.githubusercontent.com/22345961/78136559-83646800-742c-11ea-93a4-cbf3dde0b467.png)
Heres the original: 👇 
![nav_centre_section](https://user-images.githubusercontent.com/22345961/78136580-8f502a00-742c-11ea-9e0e-54cad3309e40.png)

## [REQUIRED] - REMOVE - The post date background colour.
- Change your post's date background colour to transparent. 

From this (your current): 👇 
![post_date_clone](https://user-images.githubusercontent.com/22345961/78137196-93c91280-742d-11ea-8054-dee4188aaa67.png)

To this (to match the original): 👇 
![post_date_original](https://user-images.githubusercontent.com/22345961/78137276-b6f3c200-742d-11ea-843e-a655dc1ec6c5.png)

## [REQUIRED] - CHANGE - The top content section to match the original.
Add some margin to your top three content
Form this (yours): 👇 
![post_3_box_clone](https://user-images.githubusercontent.com/22345961/78137967-da6b3c80-742e-11ea-9273-220fbfbbb696.png)

To look like this (original): 👇 
![post_3_box_original](https://user-images.githubusercontent.com/22345961/78138016-f078fd00-742e-11ea-86e8-66ffb0df7d86.png)

## [REQUIRED] - CHANGE - TNW logo is not rightly placed.
Adjust the TNW logo's padding to match the original's site.

Form this: 👇 
![tnw_clone](https://user-images.githubusercontent.com/22345961/78138597-d8ee4400-742f-11ea-99c0-5d77ef74d118.png)

To this (original): 👇 
![tnw_logo_original](https://user-images.githubusercontent.com/22345961/78138630-eb687d80-742f-11ea-9323-8ddc3e79fe00.png)

## [REQUIRED] - ADD TNW Logo
When scrolling I did expect to see the TWN logo appearing at the leftmost part of your page.
Instead, I was met with this: 👇 
![scroll_tnw_logo_clone](https://user-images.githubusercontent.com/22345961/78139469-3afb7900-7431-11ea-840e-b87712414426.png)

Expected to see: 👇 
![scroll_tnw_logo](https://user-images.githubusercontent.com/22345961/78139490-49499500-7431-11ea-822f-cd6e12fbc1c4.png)

Kindly change this. It is a requirement 
![scroll_tnw_logo_requirement](https://user-images.githubusercontent.com/22345961/78139571-68482700-7431-11ea-9022-8c80a08f8a9c.png)

## [REQUIRED] -  CHANGE - The wrapper contents.
The wrapper needs to match the original.
This is what your [latest news section], [latest funding rounds on Index.co] and the rest of the content below. looks: ⬇️ 
![below_3_section_clone](https://user-images.githubusercontent.com/22345961/78140255-63d03e00-7432-11ea-8961-020adfe6047f.png)

Change the size of your contents to match this: ⬇️ 
![Below_top_3_sections](https://user-images.githubusercontent.com/22345961/78140315-7cd8ef00-7432-11ea-9a40-808dc59da14a.png)

## [REQUIRED] - CHANGE- The Footer section.
Tweak your footer as well to match the original
From this: 🔽 
![footer_clone](https://user-images.githubusercontent.com/22345961/78140564-e22ce000-7432-11ea-8a32-4a7c4de8700b.png)

To look much like this: 🔽 
![footer](https://user-images.githubusercontent.com/22345961/78140599-f1ac2900-7432-11ea-9500-fc5fe23027d4.png)

## [REQUIRED] - Medium version changes
- The TWN logo should appear at the leftmost in a medium screen view.
This is what you have in medium view: 👇 
![medium_screen_tnw_logo_clone](https://user-images.githubusercontent.com/22345961/78141283-f32a2100-7433-11ea-859b-53e73a33ae1f.png)

This is what is required: 👇 
![medium_screen_tnw_logo](https://user-images.githubusercontent.com/22345961/78141324-03da9700-7434-11ea-9eae-072dca900aec.png)


Please make carryon with changes and submit another review request.

- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:

- When you have made the specified changes, please submit another code review. Thank you!

*Happy coding :smile:,*
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-04-01 13:47 UTC, fdfragoso commented
@christianotieno please can you clear this error to us: "[REQUIRED] - CHANGE - The top content section to match the original." - would be a thin margin between the yellow bar and the content?

2020-04-01 23:22 UTC, SofiBretz commented
### Changes required ♻️
### Hello team 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [ ] As the last TSE required 'When scrolling I did expect to see the TWN logo appearing at the leftmost part of your page.' please fix this.

- [ ] As the last TSE required 'Adjust the TNW logo's padding to match the original's site.' please make the logo at the very left side of the page, follow the original page.

**Medium screen:**

- [ ] As the last TSE required 'The TWN logo should appear at the leftmost in a medium screen view.' consider make the logo appears as the original site.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

2020-04-02 08:31 UTC, fdfragoso commented
@SofiBretz - About your comments:

- The first error, we see it solve it, is necessary for the usage of javascript. On the original web site, the logo shows up after scrolling a little bit down. We looked over the internet and everyone says to use JS.
- The second error we fixed on the first review. Our logo is on the left corner, maybe a few pixels to the right, but without any margin or padding. Comparing with the website we cant see the difference.
- It was already done. When in the middle screen size the logo on the navbar shows up.

2020-04-02 09:54 UTC, sumancrest0001 commented
[REQUIRED CHANGES] You guys have done a great job :clap: :clap: 
But we need to make a couple of changes to get a green signal.
[REQUIRED] 'When scrolling I did expect to see the TWN logo appearing at the leftmost part of your page.' I believe we can achieve the feature with CSS also. 

[Required] Please consider following images to make sure that it looks similar to the original page. For the medium and small screen.

![Screenshot from 2020-04-02 15-22-21](https://user-images.githubusercontent.com/37747619/78234971-aa3ba080-74f7-11ea-8b2f-df39ce9c1aac.png)

It should be like this.
![Screenshot from 2020-04-02 15-37-58](https://user-images.githubusercontent.com/37747619/78235202-fd155800-74f7-11ea-981d-dedb0c9fac35.png)

2020-04-02 09:58 UTC, sumancrest0001 commented
[Required] Please make 2 columns for the apps, gears section on the medium screen. Currently, its 3 columns. Do not forget to give some margins between columns. It will make your layout very good.
![Screenshot from 2020-04-02 15-25-23](https://user-images.githubusercontent.com/37747619/78235405-554c5a00-74f8-11ea-9475-3775cf8a0711.png)

It should be like this :point_down:
![Screenshot from 2020-04-02 15-25-48](https://user-images.githubusercontent.com/37747619/78235562-87f65280-74f8-11ea-9f3e-2c33ce25dcf8.png)

2020-04-02 10:05 UTC, sumancrest0001 commented
[Required] you have to make changes to the section also. Please try to emulate the same design as that of the original site.
![Screenshot from 2020-04-02 15-26-44](https://user-images.githubusercontent.com/37747619/78236019-2bdffe00-74f9-11ea-9ca3-94396f740664.png)

**It should be like this :point_down:** 
![Screenshot from 2020-04-02 15-44-11](https://user-images.githubusercontent.com/37747619/78236089-46b27280-74f9-11ea-8517-347fea3ebf5a.png)
[TIPS] Try to reduce font-size, letter-spacing, and line-height on the medium screen.

Reach out to the slack channel if you need any support. **suman shrestha**

ALL THE BEST  :+1:

2020-04-02 13:21 UTC, sumancrest0001 commented
[CHANGES REQUIRED] Nice work :+1:  :+1:  but it seems like you forgot to fix the first issue stated in the previous review. 

As the last TSE required 'When scrolling I did expect to see the TWN logo appearing at the leftmost part of your page.' the logo has to appear even when you scroll, consider follow the original page design.

**You have fixed other issues. :clap:  :clap:  :clap:** 

But while doing so, Other issues are raised. Please check the following issues and submit once again after fixing those issue.
I know we are requesting you to make changes multiple times and it could be a little bit demotivating but trust me after fixing these issue, your project looks almost the same as that of the original site.

Stay motivated and kindly make the following changes.

**In your project**

![Screenshot from 2020-04-02 19-03-01](https://user-images.githubusercontent.com/37747619/78253822-b41fcc80-7514-11ea-8b9f-95b7f95cf9a5.png)

### But it should look like this :point_down: 

![Screenshot from 2020-04-02 19-03-11](https://user-images.githubusercontent.com/37747619/78253863-ca2d8d00-7514-11ea-84a4-4bdd8f15debd.png)
[TIPS] remove justify-content: space-between property for the medium screen.

2020-04-02 13:26 UTC, sumancrest0001 commented
[REQUIRED CHANGES] We have to also change the font-size of the top articles. Please have a look and make changes. It won't take much time. 
![Screenshot from 2020-04-02 19-07-18](https://user-images.githubusercontent.com/37747619/78254430-a0c13100-7515-11ea-9c2a-ca9a601f77df.png)

### It should be :point_down:  :point_down: 
![Screenshot from 2020-04-02 19-07-39](https://user-images.githubusercontent.com/37747619/78254476-b33b6a80-7515-11ea-95fe-6a976c34e1d1.png)

2020-04-02 13:28 UTC, sumancrest0001 commented
We are very close to getting :+1: :+1:  for this project.

Feel free to contact me on slack **suman shrestna**

### Happy coding

2020-04-02 14:25 UTC, fdfragoso commented
@sumancrest0001 - Like we said before this would be done using javascript what is out of the scope for this project. If you have any suggestions on how to achieve it, great we will do it, but in the moment we can't do it.  As the last TSE required 'When scrolling I did expect to see the TWN logo appearing at the leftmost part of your page.' the logo has to appear even when you scroll, consider follow the original page design.

2020-04-02 16:16 UTC, men32z approved these changes
## Good job making the changes,

before to merge take a look on this OPTIONAL changes that would make your project even better, 
- [ ] some images are distorted, you could fix them with ` background-size: cover;` for example but there are more ways to do it. 
- [ ] fix the sticky navbar.
- [ ] try to change some images to make it look more natural and less like a template.
- [ ] take a look on the original web site fonts styles, sizes and font family, that would make your project look more professional. 
- [ ] and last but not least, try to make the required change of the logo that my collegues ask for, remember that you can use google to find solutions [like this](https://stackoverflow.com/questions/21176131/check-scrolling-with-css), and yes you are right here the best approach is using JS which is out of the scope but somewhere in the curriculum you will see JS so I guess doesn't hurt to try to implement it

![BlgS1sdIUAEybkW](https://user-images.githubusercontent.com/9115996/78264312-3df17a80-74c0-11ea-88a3-75d93f3a2d87.jpg)

### Status Approved

2020-04-02 16:16 UTC, men32z commented on style.css
> +  z-index: 99999;
change this before to merge, is causing sticky nav getting hide.
```suggestion
  top: 0;
  z-index: 99999;
```

2020-04-03 08:33 UTC, merged